; =============================================================================
; NovaVM NSIS Installer Hooks
; Developer : Vikash Kumar <https://vikukumar.github.io>
; Product   : NovaVM v1.0.0
; Year      : 2026
; License   : MIT
;
; This file is executed by Tauri's NSIS installer builder at specific
; installation lifecycle points. It handles:
;
;   PRE-INSTALL  — privilege check, OS version check
;   POST-INSTALL — WHP activation, PATH, shortcut, registry branding
;   POST-UNINSTALL — cleanup of PATH and registry entries
; =============================================================================

; ── Dynamic Branding defines (generated by metadata sync script) ────────────
!include /NONFATAL "generated_branding.nsh"

!ifndef NOVAVM_VERSION
  !define NOVAVM_VERSION "${VERSION}"
!endif
!ifndef NOVAVM_PUBLISHER
  !define NOVAVM_PUBLISHER "Vikash Kumar"
!endif
!ifndef NOVAVM_URL
  !define NOVAVM_URL "https://vikukumar.github.io"
!endif
!ifndef NOVAVM_SUPPORT_URL
  !define NOVAVM_SUPPORT_URL "${NOVAVM_URL}/support"
!endif
!ifndef NOVAVM_UPDATE_URL
  !define NOVAVM_UPDATE_URL "${NOVAVM_URL}/releases"
!endif
!ifndef NOVAVM_ABOUT_URL
  !define NOVAVM_ABOUT_URL "${NOVAVM_URL}"
!endif
!ifndef NOVAVM_COPYRIGHT
  !define NOVAVM_COPYRIGHT "© 2026 ${NOVAVM_PUBLISHER}. All rights reserved."
!endif
!ifndef NOVAVM_REG_KEY
  !define NOVAVM_REG_KEY "Software\VikashKumar\NovaVM"
!endif

; ── Pre-install hook ──────────────────────────────────────────────────────────
!macro NSIS_HOOK_PREINSTALL
  DetailPrint "NovaVM ${NOVAVM_VERSION} by ${NOVAVM_PUBLISHER}"
  DetailPrint "Homepage: ${NOVAVM_URL}"
  DetailPrint ""
  DetailPrint "Checking system requirements..."

  ; Require Windows 10 v1803+ (build 17134) for Windows Hypervisor Platform
  ${If} ${AtLeastWin10}
    DetailPrint "Windows 10 or later detected — OK"
  ${Else}
    MessageBox MB_ICONSTOP|MB_OK \
      "NovaVM requires Windows 10 version 1803 or later.$\n\
      Please upgrade your system and try again."
    Abort
  ${EndIf}

  ; Require elevated privileges
  !ifdef NSIS_INSTALLUSERLEVEL
    ; per-user install is OK
  !else
    UserInfo::GetAccountType
    Pop $0
    ${If} $0 != "Admin"
      MessageBox MB_ICONEXCLAMATION|MB_OK \
        "Administrator privileges are required to enable the Windows Hypervisor Platform.$\n\
        Please right-click the installer and choose 'Run as administrator'."
      Abort
    ${EndIf}
  !endif
!macroend

; ── Post-install hook ─────────────────────────────────────────────────────────
!macro NSIS_HOOK_POSTINSTALL

  ; ── 1. Enable Windows Hypervisor Platform (WHP) ─────────────────────────────
  ;
  ;  WHP is required for native hardware-accelerated VMs without VirtualBox/QEMU.
  ;  We call DISM (Deployment Image Servicing and Management) to enable the
  ;  "VirtualMachinePlatform" optional Windows Feature. This is a silent,
  ;  automated equivalent of running:
  ;    Enable-WindowsOptionalFeature -Online -FeatureName VirtualMachinePlatform
  ;
  ;  The feature is already present on Windows 10 v1803+ / Windows 11.
  ;  DISM exits with 0 if already enabled, 3010 if a reboot is needed.
  DetailPrint ""
  DetailPrint "=== Enabling Windows Hypervisor Platform (WHP) ==="
  DetailPrint "  This allows NovaVM to run VMs without VirtualBox or QEMU."
  DetailPrint "  (Uses the same hypervisor engine as Hyper-V)"

  ; Check if WHP is already enabled via registry
  ReadRegStr $R0 HKLM \
    "SOFTWARE\Microsoft\Windows NT\CurrentVersion\Virtualization" \
    "WHP"
  ${If} $R0 == "1"
    DetailPrint "  Windows Hypervisor Platform is already enabled."
  ${Else}
    DetailPrint "  Running: DISM /Online /Enable-Feature /FeatureName:VirtualMachinePlatform /NoRestart"
    nsExec::ExecToLog \
      '"$WINDIR\System32\dism.exe" /Online /Enable-Feature \
       /FeatureName:VirtualMachinePlatform /All /NoRestart'
    Pop $0
    ${If} $0 == 0
      DetailPrint "  WHP enabled successfully."
      WriteRegStr HKLM \
        "SOFTWARE\Microsoft\Windows NT\CurrentVersion\Virtualization" \
        "WHP" "1"
    ${ElseIf} $0 == 3010
      DetailPrint "  WHP enabled — a system restart is required to activate it."
      ; Flag for restart prompt at the end of install
      WriteRegDWORD HKLM "${NOVAVM_REG_KEY}" "PendingReboot" 1
    ${Else}
      DetailPrint "  WHP enablement returned code $0."
      DetailPrint "  You can enable it manually with (PowerShell as Admin):"
      DetailPrint "    Enable-WindowsOptionalFeature -Online -FeatureName VirtualMachinePlatform"
    ${EndIf}
  ${EndIf}

  ; ── 2. Desktop Shortcut ──────────────────────────────────────────────────────
  DetailPrint ""
  DetailPrint "Creating Desktop Shortcut..."
  CreateShortcut "$DESKTOP\NovaVM.lnk" \
    "$INSTDIR\novavm.exe" "" \
    "$INSTDIR\novavm.exe" 0 \
    SW_SHOWNORMAL \
    "" \
    "NovaVM — Native VM Manager by Vikash Kumar"

  ; ── 3. Start Menu Shortcut ───────────────────────────────────────────────────
  CreateDirectory "$SMPROGRAMS\NovaVM"
  CreateShortcut "$SMPROGRAMS\NovaVM\NovaVM.lnk" \
    "$INSTDIR\novavm.exe" "" \
    "$INSTDIR\novavm.exe" 0
  CreateShortcut "$SMPROGRAMS\NovaVM\NovaVM Website.lnk" \
    "${NOVAVM_URL}"
  CreateShortcut "$SMPROGRAMS\NovaVM\Uninstall NovaVM.lnk" \
    "$INSTDIR\uninstall.exe"

  ; ── 4. Run as Administrator compatibility flag ────────────────────────────────
  DetailPrint "Configuring Administrator Privilege Flags..."
  WriteRegStr HKLM \
    "Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers" \
    "$INSTDIR\novavm.exe" "~ RUNASADMIN"
  WriteRegStr HKCU \
    "Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers" \
    "$INSTDIR\novavm.exe" "~ RUNASADMIN"

  ; ── 5. System PATH ───────────────────────────────────────────────────────────
  DetailPrint "Adding NovaVM to System PATH..."
  ReadRegStr $0 HKLM \
    "SYSTEM\CurrentControlSet\Control\Session Manager\Environment" "Path"
  WriteRegExpandStr HKLM \
    "SYSTEM\CurrentControlSet\Control\Session Manager\Environment" \
    "Path" "$0;$INSTDIR"
  ReadRegStr $0 HKCU "Environment" "Path"
  WriteRegExpandStr HKCU "Environment" "Path" "$0;$INSTDIR"
  SendMessage 0xffff 0x001A 0 "STR:Environment" /TIMEOUT=5000

  ; ── 6. Add/Remove Programs branding ──────────────────────────────────────────
  DetailPrint "Writing Add/Remove Programs registry entries..."
  WriteRegStr HKLM \
    "Software\Microsoft\Windows\CurrentVersion\Uninstall\NovaVM" \
    "DisplayName" "NovaVM"
  WriteRegStr HKLM \
    "Software\Microsoft\Windows\CurrentVersion\Uninstall\NovaVM" \
    "DisplayVersion" "${NOVAVM_VERSION}"
  WriteRegStr HKLM \
    "Software\Microsoft\Windows\CurrentVersion\Uninstall\NovaVM" \
    "Publisher" "${NOVAVM_PUBLISHER}"
  WriteRegStr HKLM \
    "Software\Microsoft\Windows\CurrentVersion\Uninstall\NovaVM" \
    "URLInfoAbout" "${NOVAVM_ABOUT_URL}"
  WriteRegStr HKLM \
    "Software\Microsoft\Windows\CurrentVersion\Uninstall\NovaVM" \
    "URLUpdateInfo" "${NOVAVM_UPDATE_URL}"
  WriteRegStr HKLM \
    "Software\Microsoft\Windows\CurrentVersion\Uninstall\NovaVM" \
    "HelpLink" "${NOVAVM_SUPPORT_URL}"
  WriteRegStr HKLM \
    "Software\Microsoft\Windows\CurrentVersion\Uninstall\NovaVM" \
    "Comments" "${NOVAVM_COPYRIGHT}"
  WriteRegStr HKLM \
    "Software\Microsoft\Windows\CurrentVersion\Uninstall\NovaVM" \
    "DisplayIcon" "$INSTDIR\novavm.exe"
  WriteRegDWORD HKLM \
    "Software\Microsoft\Windows\CurrentVersion\Uninstall\NovaVM" \
    "NoModify" 1
  WriteRegDWORD HKLM \
    "Software\Microsoft\Windows\CurrentVersion\Uninstall\NovaVM" \
    "NoRepair" 1

  ; ── 7. NovaVM application registry key ────────────────────────────────────────
  WriteRegStr HKLM "${NOVAVM_REG_KEY}" "InstallDir"  "$INSTDIR"
  WriteRegStr HKLM "${NOVAVM_REG_KEY}" "Version"     "${NOVAVM_VERSION}"
  WriteRegStr HKLM "${NOVAVM_REG_KEY}" "Publisher"   "${NOVAVM_PUBLISHER}"
  WriteRegStr HKLM "${NOVAVM_REG_KEY}" "Homepage"    "${NOVAVM_URL}"
  WriteRegStr HKLM "${NOVAVM_REG_KEY}" "Copyright"   "${NOVAVM_COPYRIGHT}"
  WriteRegStr HKLM "${NOVAVM_REG_KEY}" "InstallDate" "$%DATE%"

  ; ── 8. Reboot prompt if WHP was freshly enabled ───────────────────────────────
  ReadRegDWORD $R1 HKLM "${NOVAVM_REG_KEY}" "PendingReboot"
  ${If} $R1 == 1
    MessageBox MB_ICONINFORMATION|MB_YESNO \
      "NovaVM has been installed successfully!$\n$\n\
      The Windows Hypervisor Platform (WHP) was enabled and requires \
      a system restart to activate.$\n$\n\
      Would you like to restart now?" \
      IDYES reboot_now IDNO skip_reboot
    reboot_now:
      Reboot
    skip_reboot:
      DetailPrint "Reboot deferred. WHP will activate after next restart."
  ${EndIf}

  DetailPrint ""
  DetailPrint "NovaVM ${NOVAVM_VERSION} installed successfully!"
  DetailPrint "Developer: ${NOVAVM_PUBLISHER} — ${NOVAVM_URL}"

!macroend

; ── Post-uninstall hook ───────────────────────────────────────────────────────
!macro NSIS_HOOK_UNPOSTINSTALL

  DetailPrint "Removing Desktop Shortcut..."
  Delete "$DESKTOP\NovaVM.lnk"

  DetailPrint "Removing Start Menu entries..."
  Delete "$SMPROGRAMS\NovaVM\NovaVM.lnk"
  Delete "$SMPROGRAMS\NovaVM\NovaVM Website.lnk"
  Delete "$SMPROGRAMS\NovaVM\Uninstall NovaVM.lnk"
  RMDir  "$SMPROGRAMS\NovaVM"

  DetailPrint "Removing Administrator Privilege Flags..."
  DeleteRegValue HKLM \
    "Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers" \
    "$INSTDIR\novavm.exe"
  DeleteRegValue HKCU \
    "Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers" \
    "$INSTDIR\novavm.exe"

  DetailPrint "Removing Add/Remove Programs entry..."
  DeleteRegKey HKLM \
    "Software\Microsoft\Windows\CurrentVersion\Uninstall\NovaVM"

  DetailPrint "Removing NovaVM registry key..."
  DeleteRegKey HKLM "${NOVAVM_REG_KEY}"

  DetailPrint "Removing from PATH..."
  ; Note: PATH cleanup is best-effort — we remove only the entry we added
  ; A full PATH clean-up would require a helper plugin (e.g. EnVar).

  DetailPrint "NovaVM has been uninstalled."
  DetailPrint "Note: Windows Hypervisor Platform remains enabled (it is a system feature)."
  DetailPrint "To disable WHP manually: DISM /Online /Disable-Feature /FeatureName:VirtualMachinePlatform"

!macroend
