[build]
# Use lld linker on Linux for faster link times
# target.x86_64-unknown-linux-gnu.linker = "clang"
# target.x86_64-unknown-linux-gnu.rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.aarch64-apple-darwin]
rustflags = []

[target.x86_64-apple-darwin]
rustflags = []
